### ISSUE TITLE
[Umbrella] test improvement

### ISSUE THREAD

**Issue by himself65** [wakujs/waku#186]
This is a list of what kinds of tests we still need. In case of the regression:

## Smoke test

- [x] Each example should work
  - [x] https://github.com/dai-shi/waku/issues/206

## E2E
- [x] Basic usage (click button, async server component)
### SSR
- [x] Should ssr render correctly on the first screen
### RSC
- [x] Should RSC work well
- [x] Should server action work well
- [x] Should server action interactive work well with local files
- [x] Dev mode should be the same as Prod mode.
### Styles #265 
- [x] css modules
- [x] vanilla-extract
- [x] stylex

### Ecosystem
- [x] RSC with CSS
- [x] RSC with some vite plugins like (alias, vanilla extract CSS...)

## Unit Test
- [x] Each single plugin should work well
- [ ] ~~RSC render worker should be predictable for each input/output~~ (we don't have worker now)

**Comment by himself65** [comment]
How do we test the serverless function like vercel, cloudflare, deno?

**Comment by himself65** [comment]
I think we can test deno and cloudflare, but not vercel. Vercel requires us to build the code in production so we can test it?

**Comment by dai-shi** [comment]
@himself65 Can you update this issue? Close is if it's no longer relevant.

**Comment by himself65** [comment]
I think we have all of the test cases. We can close
